import { LintIssue } from '../validator/types.js';

/**
 * Represents the final report generated by the Linter.
 */
export interface LintReport {
  /**
   * Indicates whether the model passed all linting checks without any errors.
   */
  valid: boolean;

  /**
   * List of issues found during linting.
   */
  issues: LintIssue[];

  /**
   * Estimates for memory requirements of the model.
   */
  memoryEstimate: {
    /**
     * Estimated memory required for parameters in bytes.
     */
    parameterMemory: number;
    /**
     * Estimated memory required for activations in bytes.
     */
    activationMemory: number;
  };
}
